### PR TITLE
#23 Resilience Resources

### PR DESCRIPTION
**Pull request by jimmyygit**
image

hmm
image
@LemonFace0309 I used ur `<TextAndPic>` component but the image is set a bit small. do you know why? Changing col width wont do anything either.
idk if this is priority issue, but if worse comes to worse, i can just use reuse my version of TextAndPic that i had earlier.

### CODE REVIEW

**Comment by functionstackx** [comment]
> @LemonFace0309 I used ur `<TextAndPic>` component but the image is set a bit small. do you know why? Changing col width wont do anything either.


@jimmyygit is there a way to expose another variable from that shared component? so that you get the functionally that you want?

remember if you expose another variable, then you have to modify all the existing references to this function

**Comment by LemonFace0309** [comment]
Add padding and margin to you a container div for your children elements

**Comment by LemonFace0309** [comment]
@jimmyygit

**Comment by LemonFace0309** [comment]
Try not to modify the shared component

**Comment by functionstackx** [comment]
@jimmyygit dont you need to do "like complete #23"  or something, or does  just #23 work

**Comment by jimmyygit** [comment]
> @jimmyygit dont you need to do "like complete #23" or something, or does just #23 work

#23 just works. I dont even need "Closing" either

**Review by wx02shi — APPROVED** [review]

**Comment by functionstackx** [comment]
@jimmyygit did you make an issue pertaining to the issues stated above or was this resolved?

**Comment by jimmyygit** [comment]
> @jimmyygit did you make an issue pertaining to the issues stated above or was this resolved?

resolved :) 
image
i guess i shouldve put this earlier

**Pull request merged**
