### PR TITLE
Bio

### LINKED ISSUE #20: About Page - Bio
image

### PR DESCRIPTION
**Pull request by LemonFace0309**
desktop:
image

mobile:
image
image

- edit: will add margins to bottom of each acknowledgement in mobile view

acknowledgements is made into a reusable component

closing #20

### CODE REVIEW

**Comment by LemonFace0309** [comment]
image

**Comment by functionstackx** [comment]
@LemonFace0309 

https://msmr-git-bio.cache-and-cookies.vercel.app/about

clear cache and do crt+shift+r

it doesn't load properly, it is just mine end or for you too?


image
image

**Comment by functionstackx** [comment]
https://stackoverflow.com/questions/62860798/preloading-images-in-nextjs

<Image> doesn't have SSG support? so the reason it is so slow cuz it needs to start the next app instead of staticly serving the images?


@jimmyygit  doesn't use the next Image tag, maybe that is why it is only effecting about page?
https://github.com/Cache-and-Cookies/msmr/blob/43c5d2451bb495134718ff477e06a7d70aeaebff/components/Landing.js#L26

**Comment by jimmyygit** [comment]
> @LemonFace0309
> 
> https://msmr-git-bio.cache-and-cookies.vercel.app/about
> 
> clear cache and do crt+shift+r
> 
> it doesn't load properly, it is just mine end or for you too?
> 
> image
> image

image
i see it fine

**Comment by jimmyygit** [comment]
> https://stackoverflow.com/questions/62860798/preloading-images-in-nextjs
> 
>  doesn't have SSG support? so the reason it is so slow cuz it needs to start the next app instead of staticly serving the images?
> 
> @jimmyygit doesn't use the next Image tag, maybe that is why it is only effecting about page?
> msmr/components/Landing.js
> 
> Line 26 in 43c5d24
> 
>  `. The banner images we're using are also huge af. ~2000x1000 is about 4x the size we realistically need

**Comment by functionstackx** [comment]
> > https://stackoverflow.com/questions/62860798/preloading-images-in-nextjs
> > doesn't have SSG support? so the reason it is so slow cuz it needs to start the next app instead of staticly serving the images?
> > @jimmyygit doesn't use the next Image tag, maybe that is why it is only effecting about page?
> > msmr/components/Landing.js
> > Line 26 in [43c5d24](https://github.com/Cache-and-Cookies/msmr/commit/43c5d2451bb495134718ff477e06a7d70aeaebff)
> >  
> oh yea. I actually just forgot to use `<Image>`. The banner images we're using are also huge af. ~2000x1000 is about 4x the size we realistically need

don't use <Image>

**Comment by LemonFace0309** [comment]
F okay, will change later. Not a big deal

**Comment by LemonFace0309** [comment]
@OrenLeung @jimmyygit just review approve for now. We can modify static file management next sprint.

**Comment by functionstackx** [comment]
> @OrenLeung @jimmyygit just review approve for now. We can modify static file management next sprint.

can you create a new issue and send the issue link to this thread?

**Comment by LemonFace0309** [comment]
> > @OrenLeung @jimmyygit just review approve for now. We can modify static file management next sprint.
> 
> can you create a new issue and send the issue link to this thread?

Yep, #50

**Review by functionstackx — APPROVED** [review]
Approved for now! :) Remember to fix this issue later

https://github.com/Cache-and-Cookies/msmr/issues/50

**Pull request merged**
