### PR TITLE
Created formating CI as referenced in #63

### LINKED ISSUE #63: Github Action CI Format Code
## Why

We have this .prettierrc file but it is enforced; pretty much optional since it isn't enforced by any tests.

https://github.com/Cache-and-Cookies/msmr/blob/development/.prettierrc

Instead of burdening the developers with another thing to remember before pushing code, this ci will auto-format code according to the .prettierrc specs.

## How

Using Github Actions and community built packages, we can auto-format on PRs.

## Resources

https://mskelton.medium.com/auto-formatting-code-using-prettier-and-github-actions-ed458f58b7df

https://github.com/mskelton/prettier-formatting-example/blob/master/package.json

https://github.com/mskelton/prettier-formatting-example/blob/master/.github/workflows/format.yml

### PR DESCRIPTION
**Pull request by functionstackx**
Using Github Actions and community built packages, we can auto-format on PRs.

on master and development

**This PR is super messy as testing the code requires a physical PR**

### CODE REVIEW

**Comment by functionstackx** [comment]
## Issue

Vercel Deploys the Preview, then the Github Action Format CI Commit's It message, then the vercel has to deploy again due to the changes

image

## Fix

Instead of setting up Vercel in the console, we have to use a github action and sync lock it is instead of async.

## Recommendation

It is kinda annoying but not a big issue. It would be a bigger issue to add all the vercel configs to an action

**Comment by OrenLeung** [comment]
@LemonFace0309 this is a thick pull request as there is a big of files that have not been "prettified"

Please review, approve, and merge ASAP to avoid merge conflicts

**Comment by functionstackx** [comment]
@LemonFace0309 

are you sure this is how you want to set up yr .prettierrc? The code output looks kinda off


image

**Review by LemonFace0309 — APPROVED** [review]
Thanks for the format :)))

**Pull request merged**
